import { promises as fs } from 'fs'
import matter from 'gray-matter'
import Link from 'next/link'
import path from 'path'
import Layout from '../components/Layout'
import { postFilePaths, POSTS_PATH } from '../utils/mdxUtils'

export default function Index({ posts }) {
  return (
    <Layout>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/posts/${post.filePath}`}
              href={`/posts/[slug]`}
            >
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  )
}

export async function getStaticProps({ locale }) {
  const posts = (await Promise.all(postFilePaths.map(async (filePath) => {
    try {
      const source = await fs.readFile(path.join(POSTS_PATH, filePath, `index${locale !== 'en' ? `.${locale}` : ''}.mdx`));
      const { content, data } = matter(source);

      return {
        content,
        data,
        filePath,
      };
    } catch (err) {
      return null;
    }
  }))).filter(p => p !== null);

  return { props: { posts }, revalidate: 10 }
}
